### PR TITLE
Chat Visibility Toggle

### PR DESCRIPTION
**Pull request by TheStonedTurtle**
Added a `/togglechat` command to the default chat resource. Does not prevent player from sending messages, only prevents them from seeing them.

### CODE REVIEW

**Comment by minipunch** [comment]
This would be awesome!

**Comment by TheStonedTurtle** [comment]
Added the `TriggerEvent('chat:clear')` as suggested by @murfasa 
Added the ability for other resources to toggle the chat visibility to a certain state. (true=Visible , false=Hidden)

**Comment by JohnnyCrazy** [comment]
I'm not a fan of discarding all the chat messages which are sent while the chat is "disabled". Hiding the chat window on JS/CSS/HTML-side would be preferred, since then the user can still read the old chat messages when he reenables his chat.

What's your opinion on this @blattersturm ?

**Comment by TheStonedTurtle** [comment]
@JohnnyCrazy, I've rewrote this to use JS/CSS/HTML like you suggested to retain chat history. It could probably be cleaned up some as well since I'm no JS pro.

**Comment by cutiestatic** [comment]
@TheStonedTurtle can you send me the whole download to this chat with the toggle on discord static#2247

**Pull request closed without merging**
