### PR TITLE
sv_chat.lua for okokChat

### PR DESCRIPTION
**Pull request by okokscripts**
This sv_chat.lua file has been modified to support okokChat.

### CODE REVIEW

**Comment by smallo92** [comment]
Use the built in chatmodes for this sort of thing. You don't need to edit the base resource. See [https://github.com/citizenfx/cfx-server-data/pull/101](https://github.com/citizenfx/cfx-server-data/pull/101) for examples.

**Comment by smallo92** [comment]
Oh wait, I thought you were trying to do an admin chat channel lol. What you are adding can be easily added in your own script using hooks there. There is no need to have this as part of the base resource.

**Comment by tabarra** [comment]
Oof  
Base resources should be framework agnostic.  
They are the base other resources should build atop, not the other way around.

**Comment by titanium-cfx** [comment]
As mentioned, base resources must be framework agnostic.
You should take a look at this pending PR on how to use chat hooks: https://github.com/citizenfx/fivem-docs/pull/234

**Comment by okokscripts** [comment]
What we were told by the cfx forum admin was to make the changes on a pull request instead of telling people what to do, so that's what we did.

We did not only add/change some thing but also removed as those things were useless to us.

**Comment by technetium-cfx** [comment]
You removed functionality from a _default_ resource because it was not useful to _you_. That's a red flag already. Framework-specific code does not belong here, and no one on the forums will have told you so. This was likely a misinterpretation.

We welcome additional default functionality or general improvements. Any change here must be relevant for everyone, not just those who use a subset of frameworks out there.

**Comment by okokscripts** [comment]
We removed the functionality because it would send a default message without any command before the message that we do not wish to have, we also changed the join and leave messages to be compatible with okokChat and added the possibility to choose if only the admins can see it.

What we were told on the forum was the following:
"Sounds like you either want to cancel the chatMessage event or use chat modes. Also if you are missing functionality in the chat resource then PR an api for it don’t tell people to make those changes."

In my understanding he tells us to not tell people to make the changes so the logic solution would be a pull request.
Do you know any other way of doing this?

**Comment by sadboilogan** [comment]
functionality doesnt mean hardcoding your own logic in, instead providing a *nice* way of being able to handle that from other resources

**Comment by technetium-cfx** [comment]
> We removed the functionality because it would send a default message without any command before the message that we do not wish to have
I'm not sure what causes that to happen, but that does not seem to originate from here.

> we also changed the join and leave messages to be compatible with okokChat and added the possibility to choose if only the admins can see it.

Modifying a default resource to be compatible with your extension should not be necessary, and is highly discouraged. The built-in ACL system should be used.

> Sounds like you either want to cancel the chatMessage event or use chat modes. Also if you are missing functionality in the chat resource then PR an api for it don’t tell people to make those changes.
This does not include removing existing functionality just because your resource doesn't need it. What they meant is that framework-agnostic changes are accepted, not this.

> Do you know any other way of doing this?
Convars, built-in ACL system, anything that doesn't depend on external frameworks.

**Comment by blattersturm** [comment]
Chat modes/message hooks are already an API that exists and the first reply to this weird PR of yours mentioned that, as did the post you are quoting.

**Comment by okokscripts** [comment]
Ok, my bad, I misunderstood, I'm now on the right path, I'm only having a slight issue, on the chat I can update the message but can't really remove it from an external script or can I? I've been searching and can't find a way to stop that message without changing the chat resource. 
Here is an image of what message I'm talking about (it may look different on the chat without any theme):
image

And one last thing, how should I go about disabling the join and leave messages?

**Pull request closed without merging**
