### PR TITLE
Adding ToggleChat 

### PR DESCRIPTION
**Pull request by BLANKxSS**
type on chat /togglechat
hidden / show the chat
 very simple

### CODE REVIEW

**Comment by blattersturm** [comment]
Hi!

Thanks for the pull request, but it does not seem to meet quality standards for inclusion by default.

Specific reasons:
* Server-side command - why?
* Very generic net event name.
* Indentation and formatting seem off.
* Does not allow showing the chat when it's, say, hidden already. (only disables it showing on message receive)

A suggestion for you (or anyone else) would be to add a key mapping command for this, similar to the Battlefield (PC game series) chat - where you can use the key to toggle between 'hidden', 'shown' and 'always shown', preferably including UI feedback for this.

**Comment by BLANKxSS** [comment]
made a better version 

this basic idea you can edit as u winch

**Comment by warxander** [comment]
`you can (or anyone else) make it better version`
LUL

**Comment by cerium-cfx** [comment]
Initial participant doesn't seem to want to improve his PR. An improved version is in https://github.com/citizenfx/cfx-server-data/pull/101

Any chat changes should be committed to that PR

**Pull request closed without merging**
